### ISSUE TITLE
Three way incompatability between Intermodal Containers, Lead, and Natural Gas

### ISSUE THREAD

**Issue by sdobz** [brevven/bzgas#11]
## Bug

When I enable these three mods
* https://mods.factorio.com/mod/bzlead 1.2.18
* https://mods.factorio.com/mod/bzgas 0.1.11
* https://mods.factorio.com/mod/IntermodalContainers 2.0.4

The recipe for packing circuits gets changed from circuits to cables:
![20230926210540_1](https://github.com/brevven/bzgas/assets/948178/310f2d28-2020-4f5a-9e7c-9a92fb4fb5cd)

## Reproduction steps:

1. Install those three mods
2. Start a new scenario in the map editor
3. Place a containerization machine (Production tab next to assembly machines)
4. Select the "load electronic circuits" recipe
5. See that it requires 4000x copper cables rather than 2000x electronic circuits

## Investigation

This line is suspicious:

`data-final-fixes.lua:42`
```lua
if not mods.bzaluminum and not mods.bzcarbon then
  util.replace_ingredients_prior_to("electronics", "electronic-circuit", "copper-cable", 2)
end
```

By adding an exclusion for the `ic-` prefix the bug was fixed and I have the change in https://github.com/brevven/bzgas/pull/12

## Notes

Recipe before:
```json
        "ic-load-electronic-circuit": {
            "category": "packing",
            "energy": 133.33333333333,
            "ingredients": [
                {
                    "amount": 1,
                    "name": "ic-container",
                    "type": "item"
                },
                {
                    "amount": 2000,
                    "name": "electronic-circuit",
                    "type": "item"
                }
            ],
            "name": "ic-load-electronic-circuit",
            "products": [
                {
                    "amount": 1,
                    "name": "ic-container-electronic-circuit",
                    "type": "item"
                }
            ]
        },
```

Recipe after:
```json
        "ic-load-electronic-circuit": {
            "category": "packing",
            "energy": 133.33333333333,
            "ingredients": [
                {
                    "amount": 1,
                    "name": "ic-container",
                    "type": "item"
                },
                {
                    "amount": 4000,
                    "name": "copper-cable",
                    "type": "item"
                }
            ],
            "name": "ic-load-electronic-circuit",
            "products": [
                {
                    "amount": 1,
                    "name": "ic-container-electronic-circuit",
                    "type": "item"
                }
            ]
        },
```

I have listed it here rather than in intermodal containers because the code for generating recipes is fairly straightforward and these two mods muck with the recipes. It took me a while to isolate, I don't know much about factorio modding but this is making my current game awkward and I can't leave a wonky bug alone. If I figure it out in the next few hours I'll put up a PR, otherwise I'll just build some more copper mines and start pumping out the cables

**Comment by tburrows13** [comment]
I've now fixed this in Intermodal Containers by ensuring that I load after BZ Natural Gas.

**Comment by brevven** [comment]
Sorry for delay. I've tried a couple loadouts and this seems to not be a problem after tburrows13's fix, so I am closing. Please let me know if it recurs.
